### ISSUE TITLE
Error trying using generator with custom type

### ISSUE THREAD

**Issue by gklijs** [gobanos/aoc-runner#2]
Hi, I really like this crate, if it wasn't for this crate, I wasn't trying to do aoc also in rust. I'm still pretty new to rust so the error might be my own fault. But right now I'm stuck on day 4 for rust as I can't get it to work with the annotations. Just running the tests does complete, but as soon as a add the '#[aoc(day4, part1)]' on the function I get 
```error[E0599]: no method named `as_ref` found for type (std::vec::Vec<usize>, std::vec::Vec<usize>, std::vec::Vec<std::vec::Vec<(usize, usize)>>) in the current scope```
 as error. I tried a couple of things, but don't really know the problem. I switched to version 0.2.0, because I thought it might help. My solution 4 is at [day4.rs](https://github.com/gklijs/advent_of_code_2018/blob/master/Rust/aoc_2018/src/day4.rs) plese let me know if I can do anything to help the issue.

**Comment by gobanos** [comment]
Hi,
Really glam to see you trying aoc in rust !

This is an known issue ([open on `cargo-aoc`](https://github.com/gobanos/cargo-aoc/issues/19)), currently the workaround is to `Box` the generator output, in your case : 
```
pub fn input_generator(input: &str) -> Data {
    ...
    Box::new( ... )
}
```
And take a `&Data` in your runner functions

**Comment by gklijs** [comment]
Thanks it's working now.
